import { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Bookmark, Search, Filter } from 'lucide-react';
import { useStore } from '@/store/useStore';

// Dynamic import since problems data is generated by sub-agent
let problemsData: any[] = [];
try {
  problemsData = require('@/data/problems').problems;
} catch { problemsData = []; }

const difficultyColors: Record<string, string> = {
  Easy: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  Medium: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
  Hard: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
};

export default function ProblemList() {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [filterDiff, setFilterDiff] = useState('All');
  const [filterTopic, setFilterTopic] = useState('All');
  const bookmarkedProblems = useStore((s) => s.progress.bookmarkedProblems);
  const toggleBookmark = useStore((s) => s.toggleBookmarkProblem);

  const topics = useMemo(() => Array.from(new Set(problemsData.map((p) => p.topic))), []);

  const filtered = useMemo(() => {
    return problemsData.filter((p) => {
      if (search && !p.name.toLowerCase().includes(search.toLowerCase()) && !String(p.number).includes(search)) return false;
      if (filterDiff !== 'All' && p.difficulty !== filterDiff) return false;
      if (filterTopic !== 'All' && p.topic !== filterTopic) return false;
      return true;
    });
  }, [search, filterDiff, filterTopic]);

  return (
    <div className="space-y-6 fade-in">
      <div>
        <h1 className="text-3xl font-bold gradient-text">Coding Problems</h1>
        <p className="text-slate-500 dark:text-slate-400 mt-1">{problemsData.length} problems across all topics</p>
      </div>

      <Card>
        <div className="flex flex-col md:flex-row gap-3">
          <div className="flex items-center gap-2 flex-1 bg-slate-100 dark:bg-slate-800/50 rounded-xl px-3 py-2">
            <Search size={16} className="text-slate-400" />
            <input
              type="text" placeholder="Search by name or LeetCode #"
              value={search} onChange={(e) => setSearch(e.target.value)}
              className="bg-transparent flex-1 focus:outline-none text-sm"
            />
          </div>
          <select value={filterDiff} onChange={(e) => setFilterDiff(e.target.value)} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent text-sm">
            <option value="All">All Difficulty</option>
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
          </select>
          <select value={filterTopic} onChange={(e) => setFilterTopic(e.target.value)} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent text-sm">
            <option value="All">All Topics</option>
            {topics.map((t) => <option key={t} value={t}>{t}</option>)}
          </select>
        </div>
      </Card>

      <div className="space-y-2">
        {filtered.map((p) => (
          <Card key={p.id} hover className="cursor-pointer" >
            <div className="flex items-center gap-4" onClick={() => navigate(`/problems/${p.id}`)}>
              <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-xs font-bold">
                #{p.number}
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-medium">{p.name}</h3>
                  {p.isPremium && <span className="text-xs px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400">Premium</span>}
                </div>
                <div className="flex items-center gap-2 mt-1 text-xs text-slate-400">
                  <span>{p.topic}</span>
                  <span>•</span>
                  <span>{p.pattern}</span>
                  {p.tags.slice(0, 3).map((t: string) => <span key={t} className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800">{t}</span>)}
                </div>
              </div>
              <span className={`text-xs px-2 py-1 rounded-full ${difficultyColors[p.difficulty]}`}>{p.difficulty}</span>
              <button
                onClick={(e) => { e.stopPropagation(); toggleBookmark(p.id); }}
                className="flex-shrink-0"
              >
                <Bookmark size={18} className={bookmarkedProblems.includes(p.id) ? 'fill-primary-500 text-primary-500' : 'text-slate-400'} />
              </button>
            </div>
          </Card>
        ))}
        {filtered.length === 0 && (
          <p className="text-center text-slate-400 py-8">No problems found. The problems data is loading...</p>
        )}
      </div>
    </div>
  );
}
